config/routes.rb
Rails.application.routes.draw do
  get "articles/search"
  devise_for :users
  resources :articles do
    resources :comments
  end
  resources :categories
  post "contacts/new"
  get 'welcome/contactos'
  resources :contacts, only: [:create, :new]
  root 'articles#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_article, only: [:update, :destroy, :create, :edit]
  before_action :authenticate_user!
  # GET /comments
  # GET /comments.json
  def index
    redirect_to root_path
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @article.comments.new(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: "Comentario Registrado Correctamente!"}
        format.json { render :show, status: :created, location: @comment.article }
      else
        format.html { redirect_to @comment.article, alert: "Problemas Con La Grabacion" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: "Comentario Actualizado Correctamente" }
        format.json { render :show, status: :ok, location: @comment.article }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, alert: "Comentario Eliminado" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      begin
        @comment = Comment.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to root_path, alert: "Este Comentario No Existe!"
      end
    end

    def set_article
      begin
        @article = Article.find(params[:article_id])
      rescue ActiveRecord::RecordNotFound
        redirect_to root_path, alert: "Este Articulo No Existe!"
      end
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:article_id, :user_id, :body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron category-form-dark space-a">
      <div class="">
        <%= simple_form_for([@article, @comment] ) do |f| %>
         <%= f.error_notification %>
          <div class="from-group row">
            <%= f.input :body, label: false, :input_html => { class:"ckeditor" } %>
          </div>&nbsp;
          <div class="from-group row">
            <div class="container text-center">
              <%= f.button :submit, "Comentar",  class: "btn btn-info col-md-3" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comments/edit.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2">
    <div class="jumbotron space-a comment-Edit-dark">
      <fieldset>
        <h1 class="text-center space-title form-title"> <%= "#{@article.title}" %></h1>
        <div class="col-12">
          <%= simple_form_for([@article, @comment] , html: { class: 'comment-form-Edit-dark' } ) do |f| %>
           <%= f.error_notification %>
            <div class="from-group row">
              <%= f.input :body, label: false, :input_html => { class:"ckeditor" } %>
            </div>
            <div class="form-group ">
              <%= f.button :submit, "Comentar", class: "btn btn-info btn-block form-btn-dark" %>
            </div>
          <% end %>
        </div>
      </fieldset>
    </div>
  </div>
</div>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Article</th>
      <th>User</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.article %></td>
        <td><%= comment.user %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_article_comment(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<div class="container">
  <div class="">
    <%= render 'form', comment: @comment %>
  </div>
</div>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>