config/routes.rb
Rails.application.routes.draw do
  get "articles/search"
  devise_for :users
  resources :articles do
    resources :comments
  end
  resources :categories
  post "contacts/new"
  get 'welcome/contactos'
  resources :contacts, only: [:create, :new]
  root 'articles#index'
end

app/models/article.rb
class Article < ApplicationRecord
  include PermissionsConcern
  has_many :comments, :dependent => :destroy
  has_many :has_categories, :dependent => :destroy
  has_many :categories, through: :has_categories
  after_create :save_categories
  belongs_to :user
  validates :title, uniqueness: true
  validates :title, :body, presence: true
  validates :title, length: {minimum: 15, too_short: "Minimo Son %{count} Caracteres." }
  validates :body, length: { minimum: 10, too_short: "Minimo Son %{count} Caracteres." }

  validate :valide_categories

  scope :ultimos, -> {order("created_at DESC")}

  scope :titulo, -> (title) { where("title LIKE ?", "%#{title}%") }

  has_attached_file :img_art,
          styles: {
             thumb:  { geometry: '320x240>', format: :png, convert_options: " -background white -gravity center -extent 300x300" }, #80x60
             medium: { geometry: '300x300>', format: :png, convert_options: " -background white -gravity center -extent 300x300" },
             big:    { geometry: '500x500>', format: :png, convert_options: " -background white -gravity center -extent 500x500" },
             ban:    { geometry: '630x315>', format: :png, convert_options: " -background white -gravity center -extent 630x315" },
             # hd:     { geometry: '1920x1680>', format: :png, convert_options: " -background white -gravity center -extent 1920x1680" },
             },
             default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img_art, content_type: /\Aimage\/.*\z/

  def categories=(value)
      @categories = value
      # raise @categories.to_yaml
  end
  def getCategories
      @categories
  end
  private
  def save_categories
      @categories.each do |category_id|
        # raise "category_id #{category_id} article_id#{self.id}"
        HasCategory.create(category_id: category_id, article_id: self.id)
      end
  end

  def valide_categories
    if self.getCategories.blank? && self.id.nil?
        errors.add(:categories, "Debe Agregar Una Categoria.!")
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_admin!, only: [:destroy]
  before_action :authenticate_editor!, only: [:edit, :update, :new, :create]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def search
    if params.has_key?(:titulo) && params[:titulo].length > 0
      @articles = Article.titulo(params[:titulo]).paginate(:page => params[:page], :per_page => 10 )
    else
      @articles = Article.all.paginate(:page => params[:page], :per_page => 10 )
    end
  end

  def index
    @articles = Article.paginate(:page => params[:page], :per_page => 10 ).ultimos
    if user_signed_in? && current_user.is_editor? && !params.has_key?(:normal)
      render :"admin_article"
    end
  end

  def show
    @comment = Comment.new
  end

  def new
    @article = Article.new
    @categories = Category.all
  end

  def edit
  end

  def update
    # @article.categories = @article.categories.ids
    respond_to do |format|
      if @article.update(article_params)
        format.html {redirect_to @article , notice: "Articulo #{@article.title} Modificado."}
        format.json {render :show, estatus: :created, location: @article}
      else
        format.html {render :edit}
        format.json {render json: @article.errors, status: :unprocessable_entity}
      end
    end
  end

  def create
    @article = current_user.articles.new(article_params)
    @article.categories = params[:categories]
    respond_to do |format|
      if @article.save
         format.html {redirect_to @article , notice: "Articulo #{@article.title} Registrado."}
         format.json {render :show, estatus: :created, location: @article}
      else
         format.html { render :new }
         format.json {render json: @article.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    if @article.destroy
      respond_to do |format|
        format.html {redirect_to article_path, alert: "Articulo Eliminado"}
        format.json {head :no_content}
      end
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :categories, :img_art)
  end
  def set_article
    begin
      @article = Article.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path, alert: "Este Articulo Ya No Existe"
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="col-sm-12 col-md-6 col-lg-4 article-salto article-dark space-a salto">
  <div class="card h-100 article-container article-dark">
    <div class="card-body ">
      <%= link_to article do %>
        <%= image_tag article.img_art , class: "card-img-top" %>
        <h5 class="card-title"><%= link_to truncate(article.title , length: 20), article, class: "article-title-dark"  %></h5>
        <p class="card-text"> <%= truncate_html(article.body.html_safe, length: 100 , class: "article-body-dark")  %></p>        
        <%temporal = "Categorias: "%>
        <% article.categories.each do |category| %>
        <% temporal = "#{temporal} #{category.name}" %>
        <%end%>
        <p class="article-categoria-body-dark"> <%= temporal %> </p>
      <%end%>
    </div>
  </div>
</div>

app/views/articles/_formulario.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron category-form-dark space-a">
      <h1 class="text-center space-title form-title"><%= "#{titulo} Articulo" %></h1>
      <div class="">
        <%= simple_form_for @article do |f| %>
         <%= f.error_notification %>
          <div class="fomr-group row">
            <%= f.label "Titulo: ", class:"offset-md-2 col-md-3 col-form-label text-right space-label-right" %>
            <%= f.input :title , label: false,  autofocus: true, placeholder:"Titulo De Articulo" , autocomplete: "title",require:true, class: "col-md-4 form-control" %>
          </div>
          <div class="fomr-group row">
            <%= f.label "Banner: ", class:"offset-md-2 col-md-3 col-form-label text-right space-label-right" %>
            <%= f.input :img_art , label: false, as: :file ,   autofocus: true, placeholder:"Imagen" , autocomplete: "title",require:true, class: "col-md-4 form-control" %>
          </div>
          <div class="table-responsive">
            <%= f.input :body, label: false,  autofocus: true, autocomplete: "body", require: true ,
                :as => :trix_editor, :input_html => { placeholder:"Cuerpo Del Articulo Por Crear" , 'rows' => 5, 'cols' => 29 } %>
          </div>
          <div class="">
              <% Category.all.each do |category| %>
                <%= check_box_tag "categories[]", category.id %> <%= category.name %>
              <%end%>
          </div>&nbsp;
          <div class="from-group row">
            <div class="container text-center">
              <%= f.button :submit, "Enviar",  class: "btn btn-info col-md-3" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/articles/admin_article.html.erb
<div class="jumbotron space-a table-responsive Admin-dark">
  <h1 class="Admin-title-dark">Adminitrador</h1>
  <p class=""> <%= link_to "Normal", articles_path(normal: true), class: "btn btn-success Admin-btn-dark" %> </p>
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover dataTables-example">
          <thead class="thead-dark">
            <tr>
              <th class="text-center  footable-visible footable-first-column footable-sortable active Admin-th-dark">Titulo</th>
              <th class="text-center  footable-visible footable-first-column footable-sortable active Admin-th-dark">Fecha</th>
              <th class="text-center  footable-visible footable-first-column footable-sortable active Admin-th-dark">Acciones</th>
            </tr>
          </thead>
          <tbody>
            <% @articles.each do |art| %>
              <tr class="white-text text-center Admin-tr-dark">
                <td class=""> <%= art.title %> </td>
                <td class=""> <%= art.created_at.strftime("%d-%m-%Y %H:%M") %> </td>
                <td class="text-center">
                  <%= link_to "  ", art, class: "fa fa-eye  btn btn-info"%>&nbsp;
                  <%= link_to "  ", edit_article_path(art), class: "fa fa-pencil-square-o  btn btn-warning"%>&nbsp;
                  <%= link_to "  ", art, method: :delete, data: { :confirm => "Estás seguro? de Eliminar El Articulo #{art.title}"} , class: "fa fa-trash-o btn btn-danger"%>
                </td>
              </tr>
            <%end%>
            <% unless @articles.present? %>
               <tr>
                  <h2 class="text-center">No Hay Informacion Solicitada</h2
               </tr>
            <%end%>
          </tbody>
        </table>
        <div class="flickr_pagination" style="margin-top: 20px; margin-bottom: 20px;">
          <%= will_paginate @articles %>
        </div>
      </div>
</div>

app/views/articles/edit.html.erb
<div class="container">
  <div class="">
    <%= render "formulario" , article: @article, titulo: "Editar" %>
  </div>  
</div>

app/views/articles/index.html.erb
<div class="container-fluid espaciotabla">
  <div class="row">
      <%=  render @articles  %>
      <div class="flickr_pagination" style="margin-top: 20px; margin-bottom: 20px;">
        <%= will_paginate @articles %>
      </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="">
    <%= render "formulario", article: @article, titulo: "Nuevo" %>
  </div>  
</div>

app/views/articles/search.html.erb
<div class="space-a">
  <div class="jumbotron color-e search-jumbotron search-dark">
    <div class="row search-body-dark">
      <% @articles.each do |articulo| %>
        <div class="col-md-6 search-fondo">
          <h1><%= link_to articulo.title, articulo, class: "search-title search-title-dark" %></h1>
          <p class="search-body"> <%= truncate_html(articulo.body, length: 300) %> </p>
          <p class="text-right"><%= link_to "Ver Mas", articulo, class: "btn btn-success search-btn-dark" %></p>
        </div>
      <%end%>
    </div>
    <div class="flickr_pagination" style="margin-top: 20px; margin-bottom: 20px;">
      <%= will_paginate @articles %>
    </div>
    <% unless @articles.present? %>
        <h2 class="text-center">No Hay Informacion Solicitada Con <%= "\" #{params[:titulo]} \"" %></h2>
        <p class="text-center">Lo Siento...</p>
    <%end%>
  </div>
</div>

app/views/articles/show.html.erb
<div class="jumbotron space-a show-dark">
  <% if user_signed_in? %>
    <div class="row">
      <div class="col-10">
          <h1 class="H1 card-title title-show-dark"><%= @article.title %></h1>
      </div>
      <div class="col-2">
        <div class="botonContainer">
          <% if user_signed_in? && current_user.is_editor? %>
            <%= link_to "Editar" , edit_article_path(@article), class: "btn btn-warning float-right show-btn-dark" %>
          <%end%>
        </div>
      </div>
    </div>
  <%end%>
  <div class="row">
      <% if !@article.user.nil? %>
        <p class="show-user-email-dark"><%= @article.user.email %></p> &nbsp;
      <%end%>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= image_tag @article.img_art, class: "img-fluid" , alt: "Volver a Insertar Banner!" %>
    </div>
  </div>
  <div class="article-html space-a space-b show-body-dark">
    <p class="card-text body-show-dark"><%= truncate_html(@article.body.html_safe, length: 100) %></p>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="show-categories-dark">
        <h3 class="H3">Categorias:</h3>
        <% @article.categories.each do |category| %>
            <span class="badge badge-primary show-badge-dark"><strong><%= category.name %></strong></span>
        <%end%>
      </div>
    </div>
  </div><hr class="HR-dark">
  <div class="">
    <div class="comments-container comments-dark">
      <h1 class="Show-H1-dark"><i class="fa fa-comments"></i> Comentarios <a href="#" class="Show-H1-dark">Blog.com</a></h1>
      <ul id="comments-list comment-list-dark" class="comments-list UL">
        <% @article.comments.each do |comment| %>
          <li class="LI">
              <div class=" comment-main-level">
                <div class="comment-box">
                  <div class=" comment-head">
                    <h6 class="comment-name by-author card-title"><a href="#"></a><%= truncate_html(comment.user.email.html_safe) %></h6>
                    <span><%= comment.created_at.strftime("%d-%m-%Y %H:%M") %></span>
                    <% if user_signed_in? && current_user == comment.user %>
                      <p class="I" data-toggle="tooltip" title="Eliminar" ><%= link_to '' , [@article, comment], data: { confirm: "Estas Seguro? "}, method: :delete , class: "caneca I fa fa-trash-o" %></p>
                      <p class="I" data-toggle="tooltip" title="Editar"> <%= link_to '' , edit_article_comment_path(@article, comment), class: "lapiz I fa fa-pencil-square-o" %> </p>
                    <%end%>
                  </div>
                  <div class=" comment-content">
                    <p class="card-text"><%= truncate_html(comment.body.html_safe, length: 100) %></p>
                  </div>
                </div>
              </div>
          </li>
        <%end%>
      </ul>
      <div class="space-b">
        <% unless @article.comments.present? %>
            <h2 class="text-center">No Hay Comentarios</h2>
        <%end%>
      </div>
    </div><hr class="HR-dark">
    </div>
  <% if user_signed_in? %>
    <div class="">
      <%= render "comments/form" , comment: @comment%>
    </div>
  <%end%>
</div>