config/routes.rb
Rails.application.routes.draw do
  get "articles/search"
  devise_for :users
  resources :articles do
    resources :comments
  end
  resources :categories
  post "contacts/new"
  get 'welcome/contactos'
  resources :contacts, only: [:create, :new]
  root 'articles#index'
end

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success NAV-dark">
  <a class="navbar-brand" href=" <%= root_path %> ">Blog</a>
  <button class="navbar-toggler NAV-btn-dark" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <%= link_to "Inicio", root_path , class: "nav-link bueno" %>
      </li>
      <li class="nav-item ">
        <%= link_to "Contactos", contacts_new_path , class: "nav-link bueno" %>
      </li>
      <% if user_signed_in? %>
        <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "nav-link bueno" %>
      <%else%>
        <%= link_to "Iniciar Sesión", new_user_session_path, class: "nav-link bueno"  %>
        <%= link_to "Registrarse", new_user_registration_path, class: "nav-link bueno" %>
      <%end%>
    </ul>
    <%= form_tag articles_search_path, :method => 'get', class: "form-inline my-2 my-lg-0" do %>
        <%= text_field_tag :titulo, params[:titulo], class: "form-control mr-sm-2" %>
        <%= submit_tag "Search", :name => nil , class: "btn btn-light my-2 my-sm-0" %>
    <%end%>&nbsp;
    <div class="nav-item">
      <button type="button" data-toggle="tooltip" title="Cambiar Tema" class="switch" id="switch">
        <span> <i class="fa fa-sun-o"></i> </span>
        <span> <i class="fa fa-moon-o"></i> </span>
      </button>
    </div>
  </div>
</nav>

app/views/partials/_notificaciones.html.erb
<% if !notice.nil? %>
    <div class="alert alert-dismissible alert-info">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h4 class="alert-heading">Noticia!</h4>
      <p class="mb-0"><%= notice %></p>
    </div>
<%end%>
<% if !alert.nil? %>
    <div class="alert alert-dismissible alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h4 class="alert-heading">Alert!</h4>
      <p class="mb-0"><%= alert %></p>
    </div>
<%end%>

app/views/partials/_panel.html.erb
<% if user_signed_in? %>
  <% if current_user.is_editor? %>
    <div class="list-group space-a Panel-dark">
        <%= link_to "Administrador", root_path, class: "Panel-head-dark text-center list-group-item list-group-item-action active" %>
        <%= link_to "Ver Articulos", articles_path, class: "Panel-body-dark list-group-item list-group-item-action" %>
        <%= link_to "Crear Articulo", new_article_path, class: "Panel-body-dark list-group-item list-group-item-action" %>
        <%= link_to "Ver Categorias", categories_path, class: "Panel-body-dark list-group-item list-group-item-action" %>
        <%= link_to "Crear Categoria", new_category_path, class: "Panel-body-dark list-group-item list-group-item-action" %>
    </div><br>
  <%end%>
<%end%>
  <div class="list-group space-a space-b Panel-dark">
    <%= link_to "Categorias", categories_path, class:"Panel-head-dark text-center list-group-item list-group-item-action active" %>
    <% @categorias.each do |categoria| %>
      <%= link_to categoria.name , categoria, class:"Panel-body-dark list-group-item list-group-item-action" %>
    <%end%>
  </div>