config/routes.rb
Rails.application.routes.draw do
  get "articles/search"
  devise_for :users
  resources :articles do
    resources :comments
  end
  resources :categories
  post "contacts/new"
  get 'welcome/contactos'
  resources :contacts, only: [:create, :new]
  root 'articles#index'
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :has_categories, dependent: :restrict_with_error
  has_many :articles, through: :has_categories, dependent: :restrict_with_error
  belongs_to :user
  validates :name, :color, presence: true
  validates :name, length: { in: 7..20 }
  validates :color, length: { in: 4..8 }

  has_attached_file :img_cat,
        styles: {
           medium: { geometry: '300x300>', format: :png, convert_options: " -background white -gravity center -extent 300x300" },
           },
           default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img_cat, content_type: /\Aimage\/.*\z/
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_editor!, only: [:edit, :update, :new, :create]
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:destroy]
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    if user_signed_in? && current_user.is_editor? && !params.has_key?(:normal)
      render :"admin_category"
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @articles = @category.articles.paginate(:page => params[:page], :per_page => 10 )
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = current_user.categories.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'La categoría se creó correctamente.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'La categoría se actualizó correctamente.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    if @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url, alert: "La categoría #{@category.name} fue destruida con éxito." }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to categories_url, alert: "No Se Puede Eliminar La Categoria #{@category.name} Por Que Contiene Articulos" }      
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      begin
        @category = Category.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to root_path, alert: "Esta Categoria No Existe!"
      end
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :color, :img_cat)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<style type="text/css" media="screen">
  <%= ".#{category.name.delete(' ')}" %>{
    background: <%= category.color %> !important;
  }
</style>
<div class="col-md-3">
  <div class="card space-b">
    <div class="category-container">
        <div class="card-body <%= "#{category.name.delete(' ')}" %>">
          <%= link_to category do %>
          <h2 class="card-title text-center"><%= category.name %></h2>
          <%= image_tag category.img_cat , class: "card-img-top" %>
          <%end%>
          <div class="">
            <p> <%= "Contiene #{category.articles.count} articu(s)" %>  </p>
          </div>
          <div class="card-footer">
            <%= "Creado #{category.created_at.strftime("%d-%m-%Y")}"  %>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron category-form-dark space-a">
      <h1 class="text-center space-title form-title"><%= "#{titulo} Categoria" %></h1>
      <div class="">
        <%= form_with(model: category, local: true) do |form| %>
            <% if category.errors.any? %>
                <div class="" id="error_explanation">
                  <h2 class=""> <%= pluralize(category.errors.count, "error") %> Prohibido Guardar De Esta Forma La Categoría: </h2>
                  <ul class="">
                    <% category.errors.full_messages.each do |message| %>
                        <li class=""> <%= message %> </li>
                    <%end%>
                  </ul>
                </div>
            <%end%>
            <div class="form-group row">
              <%= form.label "Nombre: ", class:"offset-md-2 col-md-3 col-form-label text-right space-label-right" %>
              <%= form.text_field :name, class: "col-md-4 form-control" %>
            </div>
            <div class="form-group row">
              <%= form.label "Banner: ", class:"offset-md-2 col-md-3 col-form-label text-right space-label-right" %>
              <%= form.file_field :img_cat, class: "col-md-4 form-control" %>
            </div>
            <div class="form-group row">
              <%= form.label "Color: ", class:"offset-md-2 col-md-3 col-form-label text-right space-label-right" %>
              <%= form.color_field :color, id: :category_color, class:"col-md-4 form-control" %>
            </div>
            <div class="form-group row">
              <div class="container text-center">
                <%= form.submit "Enviar", class:"btn btn-info col-md-3" %>
              </div>
            </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/categories/admin_category.html.erb
<div class="jumbotron space-a table-responsive Admin-dark">
  <h1 class="Admin-title-dark">Adminitrador</h1>
  <p class=""> <%= link_to "Normal", categories_path(normal: true), class: "btn btn-success Admin-btn-dark" %> </p>
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover dataTables-example">
        <thead class="thead-dark">
          <tr>
            <th class="text-center  footable-visible footable-first-column footable-sortable active Admin-th-dark">Titulo</th>
            <th class="text-center  footable-visible footable-first-column footable-sortable active Admin-th-dark">Fecha</th>
            <th class="text-center  footable-visible footable-first-column footable-sortable active Admin-th-dark">Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |cat| %>
            <tr class="Admin-tr-dark">
              <td class=""> <%= cat.name %> </td>
              <td class=""> <%= cat.created_at.strftime("%d-%m-%Y %H:%M") %> </td>
              <td class="text-center">
                <%= link_to " Ver ", cat, class: "fa fa-eye  btn btn-info"%>&nbsp;
                <%= link_to " Editar ", edit_category_path(cat), class: "fa fa-pencil-square-o  btn btn-warning"%>&nbsp;
                <%= link_to " Eliminar ", cat, method: :delete, data: { :confirm => "Estás seguro? de Eliminar La Categoria #{cat.name}"} , class: "fa fa-trash-o btn btn-danger"%>
              </td>
            </tr>
          <%end%>
          <% unless @categories.present? %>
             <tr>
                <h2 class="text-center">No Hay Informacion Solicitada</h2
             </tr>
          <%end%>
        </tbody>
      </table>
    </div>
</div>

app/views/categories/edit.html.erb
<%= render 'form', category: @category, titulo: "Editar " %>

app/views/categories/index.html.erb
<div class="row space-a">
  <%= render @categories %>
</div>

app/views/categories/new.html.erb
<%= render 'form', category: @category , titulo: "Nueva "%>

app/views/categories/show.html.erb
<style type="text/css" media="screen">
  .jumbotron{
    margin-top: 10px !important;
  }
  .category-show{
    background: <%= @category.color %> !important;
  }
</style>
<div class="category-show space-a">
    <h1 class="text-center"><strong><%= @category.name %></strong></h1>
    <h5 class="text-center">
      <div class="">
        <% if !@category.user.nil? %>
          Creado Por <strong> <%= @category.user.email %> </strong>
        <%end%>
      </div>
    </h5>
</div>
<div class="row">
  <%= render @articles %>
</div>
<div class="flickr_pagination" style="margin-top: 20px; margin-bottom: 20px;">
  <%= will_paginate @articles %>
</div>